// Authentication based types
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';

// Show Alert type
export const SHOW_ALERT = 'SHOW_ALERT';

// Room based types
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const ROOM_CONNECTED_TO_CHANNEL = 'ROOM_CONNECTED_TO_CHANNEL';
export const USER_LEFT_ROOM = 'USER_LEFT_ROOM';
export const ROOM_PRESENCE_UPDATE = 'ROOM_PRESENCE_UPDATE';


// User Rooms based types
export const FETCH_USER_ROOMS_SUCCESS = 'FETCH_USER_ROOMS_SUCCESS';
export const ROOM_JOINED = 'ROOM_JOINED';

// Socket based types
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';

// Message based types
export const MESSAGE_CREATED = 'MESSAGE_CREATED';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
